New update, benning work in 2st option

diff --git a/main b/main
--- a/main
+++ b/main
@@ -66,25 +66,51 @@ __vul(){
 	esac
 
 	# Make the attack
-	echo "Benning attack using diferents user agents ;)"
+	echo -e "\033[33mBenning attack using diferents user agents ;)\033[32m"
 	cd pagodo/
 	echo "It will to delay..."
-	python3 pagodo.py -d $target -g google_dorks.txt -l 100 -s -e 1.0
+	# It's good? Then go go go go
+	python3 pagodo.py -d $target -g google_dorks.txt -l 40 -s -e 1
 	if [ "$?" = "0" ]
 	then
-		mv pagodo/$target.txt reports/ &&
+		mv $target.txt ../reports/ &&
 			echo "Finalized attack to $target, see in reports/$target.txt" || 
 			echo -e "\033[31mThe file dont has been saved\033[32m"
 	else
-		echo -e "Error: in \033[31mpagodo.py\033[32m"
+		echo -e "Error: in \033[31mpagodo.py\033[32m\nTente: pip3 install -r requirements.txt"
 	fi
 	cd ../
-
-
 }
 
 __wordlist(){
-	echo "a"
+	# Check arguments
+	if [ "$1" ]
+	then
+		echo "Attacking $1"
+		target="$1"
+	else
+		printf "Target is: $1"; read target
+	fi
+
+	# Make the attack
+	echo -e "\033[33mBenning attack, with Google indexations\033[32m"
+	cd pagodo/
+	# It's good? Then go go go go
+	python3 pagodo.py -d $target -g blank.txt -l 300 -s -e 1
+	if [ "$?" = "0" ]
+	then
+		# Check if exists directory
+		test -d ../reports/db &&
+			echo -e "reports/db ... \033[34mok\033[32m" ||
+			mkdir ../reports/db
+		# Check if be ok
+		mv $target.txt reports/db/ &&
+			echo -e "Finalized search to $target, database\nhas been saved in reports/db/$target.data" || 
+			echo -e "\033[31mThe file dont has been saved\033[32m"
+	else
+		echo -e "Error: in \033[31mpagodo.py\033[32m\nTente: pip3 install -r requirements.txt"
+	fi
+	cd ../
 }
 
 #	Menu
@@ -117,7 +143,7 @@ else
 			exit 0	
 			;;
 		--v* | "-v")
-			echo "find to vulners"
+			echo "Find to vulnerabilties"
 			__vul "$2"
 			exit 0
 			;;
